- type: entity
  parent:
  - MCItem
  - MCWeaponGun
  - MCAttachableHolder
  id: MCWeaponSmartGun
  abstract: true
  components:
  - type: MeleeWeapon
    attackRate: 1
    damage:
      types:
        MCBrute: 20
    soundHit:
      collection: GenericHit
