- type: entity
  parent: BaseItem
  id: MCWeaponEnergyBase
  abstract: true
  components:
  - type: Sprite
  - type: Clothing
    slots:
    - Back
    - SuitStorage
  - type: Item
    size: Huge
  - type: AmmoCounter
  - type: Gun
    fireRate: 2
    selectedMode: SemiAuto
    availableModes:
    - SemiAuto
    soundGunshot:
      path: /Audio/Weapons/Guns/Gunshots/laser.ogg
  - type: MagazineAmmoProvider
  - type: ItemSlots
    slots:
      gun_magazine:
        name: Magazine
        insertSound: /Audio/Weapons/Guns/MagIn/batrifle_magin.ogg
        ejectSound: /Audio/Weapons/Guns/MagOut/batrifle_magout.ogg
        whitelist:
          tags:
          - MCBatteryTerra
  - type: Appearance
  - type: ContainerContainer
    containers:
      gun_magazine: !type:ContainerSlot
  - type: Wieldable
