- type: entity
  parent: MCItem
  id: MCAutoInjector
  name: auto injector
  description: An auto injector.
  abstract: true
  components:
  - type: Tag
    tags:
    - MCAutoInjector
  - type: Appearance
  - type: Sprite
    sprite: _MC/Objects/Medical/autoinjectors.rsi
    layers:
    - state: autoinjector-1
      map: ["enum.SolutionContainerLayers.Fill"]
  - type: SolutionContainerVisuals
    solutionName: pen
    maxFillLevels: 3
    changeColor: false
    emptySpriteName: autoinjector-1x
  - type: Item
    size: Tiny
  - type: Hypospray
    solutionName: pen
    injectSound: /Audio/_RMC14/Medical/hypospray.ogg
    transferAmount: 10
    injectOnly: true
    onlyAffectsMobs: false
    canContainerDraw: true
  - type: SolutionContainerManager
    solutions:
      pen:
        maxVol: 30
  - type: IconLabel
    textColor: White
    storedOffset: 0, -12
  - type: RMCSmartFridgeInsertable
  - type: ExaminableSolution
    solution: pen
#  - type: RefillableSolution Кривая визуализация спрайта будет
#    solution: pen

- type: Tag
  id: MCAutoInjector
