- type: entity
  parent: MCItem
  id: MCBoxBullets
  name: rifle ammunition box (???)
  description: An unknown ammunition box. It comes with a leather strap allowing to wear it on the back.
  abstract: true
  components:
  - type: Item
    size: Huge
  - type: Sprite # Мы не RMC14
    sprite: _MC/Objects/Weapons/Guns/Ammunition/Boxes/10x265.rsi
    state: 10x265mm
  - type: Appearance
  - type: InteractedBlacklist
    blacklist:
      components:
      - Xeno
  - type: Clothing
    quickEquip: false
    slots:
    - Back
    - Belt
  - type: DropOnUseInHand
  - type: BulletBox # Хуйня, под MC нужно сделать
  - type: Tag
    tags:
    - MCAmmoBox

- type: Tag
  id: MCAmmoBox
